# Generated by Django 5.0.2 on 2025-01-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Интсрумент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
    ]
